version: "2"
services:
  kibana:
    platform: linux/amd64
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
      - "5601:5601"
    # environment:
    #   - ELASTICSEARCH_HOSTS=http://elastic:9200